#pragma once

#define SPECTER_NAMESPACE_NAME 	sp

#define SPECTER_NAMESPACE		SPECTER_NAMESPACE_NAME ::

#define SPECTER_NAMESPACE_BEGIN	namespace SPECTER_NAMESPACE_NAME {
#define SPECTER_NAMESPACE_END	}